language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.0
before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
script:
    - dotnet restore
    - dotnet build 
cache:
  directories:
    - '$HOME/.nuget/packages'
    - '$HOME/.local/share/NuGet/Cache' 
