version: '3.4'
services:
  yawlrouter:
    image: mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim
    build:
      context: .
      dockerfile: Src/YawlUrl.Web.Router/Dockerfile
    ports:
      - 5000:80
    environment: 
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
     - yawldb
  yawldb:
    image: mongo
    restart: always
    ports:
     - 27017:27017