version: '3.4'
services:
  yawlapi:
    image: mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim
    build:
      context: .
      dockerfile: Src/YawlUrl.Web.Api/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - yawldb
      - yawlrouter
  yawlrouter:
    image: mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim
    build:
      context: .
      dockerfile: Src/YawlUrl.Web.Router/Dockerfile
    ports:
      - 5000:80
    depends_on:
     - yawldb
  yawldb:
    image: mongo
    restart: always
    ports:
     - 27017:27017